JSONDecodeError: Expecting value: line 2 column 1 (char 1)
TIME: 2021-07-27 13:34:28.356139
*** format_exception:
Traceback (most recent call last):

  File "E:\Projects\TWIN_parse\services\twinService.py", line 62, in work
    data = self._parse_file(fpath)

  File "E:\Projects\TWIN_parse\services\twinService.py", line 93, in _parse_file
    fdata = self._ifile.get(fpath)

  File "E:\Projects\TWIN_parse\interfaces\files\jsonInterface.py", line 38, in get
    return json.load(fp)

  File "E:\Progs\Python38_32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),

  File "E:\Progs\Python38_32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)

  File "E:\Progs\Python38_32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "E:\Progs\Python38_32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
